/**
 * src/features/clients/types/client.ts
 *
 * Domain entities and Data Transfer Objects (DTOs) for the Client module.
 * All frontend properties strictly use camelCase.
 * Mapping from Supabase snake_case will be handled at the query level.
 */

/**
 * Base Client Interface
 * Represents the complete client record as consumed by the UI.
 */
export interface Client {
  /** Unique identifier generated by Supabase (UUID) */
  id: string;
  /** Full name of the client or contact person */
  name: string;
  /** Primary contact email address */
  email: string;
  /** Optional contact phone number */
  phone?: string | null;
  /** Optional company or organization name */
  company?: string | null;
  /** ISO 8601 Timestamp of creation */
  createdAt: string;
  /** ISO 8601 Timestamp of last update */
  updatedAt: string;
}

/**
 * Data Transfer Object for Creating a Client
 * Omits auto-generated fields (id, timestamps) which are handled by the PostgreSQL database.
 */
export type CreateClientDTO = Omit<Client, "id" | "createdAt" | "updatedAt">;

/**
 * Data Transfer Object for Updating a Client
 * Wraps the CreateClientDTO in a Partial utility, allowing granular updates.
 */
export type UpdateClientDTO = Partial<CreateClientDTO>;
