/**
 * src/features/clients/types/client.ts
 *
 * Domain entities and Data Transfer Objects (DTOs) for the Client module.
 * All frontend properties strictly use camelCase.
 * Mapping from Supabase snake_case will be handled at the query level.
 */

/**
 * Base Client Interface
 * Represents the complete client record as consumed by the UI.
 */
export interface Client {
  /** Unique identifier generated by Supabase (UUID) */
  id: string;
  /** Full name of the client or contact person */
  name: string;
  /** Primary contact email address */
  email: string;
  /** Optional contact phone number */
  phone?: string | null;
  /** Optional company or organization name */
  company?: string | null;
  /** ISO 8601 Timestamp of creation */
  createdAt: string;
  /** ISO 8601 Timestamp of last update */
  updatedAt: string;
}

/**
 * Data Transfer Object for Creating a Client
 * Omits auto-generated fields (id, timestamps) which are handled by the PostgreSQL database.
 */
export type CreateClientDTO = Omit<Client, "id" | "createdAt" | "updatedAt">;

/**
 * Data Transfer Object for Updating a Client
 * Wraps the CreateClientDTO in a Partial utility, allowing granular updates.
 */
export type UpdateClientDTO = Partial<CreateClientDTO>;

/**
 * Metadata accompanying paginated API responses.
 * Used by the UI to render pagination controls and display total record counts.
 */
export interface PaginationMeta {
  /** Total number of records matching the current query in the database */
  totalRecords: number;
  /** The current active page number */
  currentPage: number;
  /** Total number of available pages based on the limit */
  totalPages: number;
  /** Boolean flag indicating if a subsequent page exists */
  hasNextPage: boolean;
  /** Boolean flag indicating if a preceding page exists */
  hasPreviousPage: boolean;
}

/**
 * Standardized wrapper for paginated API responses.
 * Ensures the data payload and calculation metadata are always delivered together.
 */
export interface PaginatedResponse<T> {
  /** The array of requested domain entities */
  data: T[];
  /** Pagination metadata for UI rendering */
  meta: PaginationMeta;
}

/**
 * Query parameters accepted by the Client service layer for fetching records.
 */
export interface ClientQueryOptions {
  /** The specific page of results to retrieve (1-indexed) */
  page?: number;
  /** The maximum number of records to return per page */
  limit?: number;
  /** Optional search string to filter records by name, email, or company */
  search?: string;
}
